### PR TITLE
Fix more warnings

### PR DESCRIPTION
**Pull request by jgunthorpe**
Here is another set of warning and style cleanups that brings infiniband-diags closer to passing rdma-core's suite of static checkers. In particular this makes it almost sparse clean.

### CODE REVIEW

**Comment by nmorey** [comment]
Looks good to me

**Review by iweiny — COMMENTED** [review]
Is there a reason you did not change the defines in include/ibdiag_common.h?

I've got them changed and I'll squash in unless you found some issue there.

Also, this brings up a good point WRT the use of defines in ib_types.h which comes from the opensm package.  A long time ago I thought it best to get all the Management defines to be part of umad...  Some of them are in umad_*.h headers but not the ones I'm converting in ibdiag_common.h  So should we move some of these defines over to a header in rdma_core?  How much management do you want there?

Example is the define for IB_PORT_EXT_CAP_IS_FEC_MODE_SUPPORTED.

**Comment by jgunthorpe** [comment]
I ultimately deleted those defines from ibdiag_common.h from my tree so they didn't get caught by sed. No harm to switch them too.

See here

https://github.com/jgunthorpe/rdma-plumbing/commit/719d046ce690f8cf2e40b51a32eb03df20a84b2d

For what I'm thinking to do for ib_types, at least as an interm step.

**Comment by weiny2** [comment]
I took these by pushing after testing the build etc...  So closing this request.

**Pull request closed without merging**
